### Open a file
GET http://localhost:8080/files/open?path=/path/to/your/file
Content-Type: application/json

### List contents of a directory
GET http://localhost:8080/files/ls?path=/path/to/your
Content-Type: application/json

### Read a file by ID
GET http://localhost:8080/files/read?id=2
Content-Type: application/json

### Delete a file or directory by ID
DELETE http://localhost:8080/files/del?id=1
Content-Type: application/json

### Update a file or directory's FCB
PUT http://localhost:8080/files/update
Content-Type: application/json

{
  "id": 1,
  "name": "updated_name",
  "parent_id": 0
}

### Create a file
POST http://localhost:8080/files/create?path=/path/to/your/newfile.txt
Content-Type: application/json

### Create a directory
POST http://localhost:8080/files/mkdir?path=/path/to/your
Content-Type: application/json
