### 测试创建文件夹
POST http://localhost:8080/files/createDir
Content-Type: application/json

{
  "name": "New Folder",
  "size": 0,
  "is_dir": true,
  "parent_id": ""
}


### 测试创建文件
POST http://localhost:8080/files/createDir
Content-Type: application/json

{
  "name": "example.txt",
  "size": 12345,
  "is_dir": false,
  "parent_id": ""
}


### 测试上传文件
POST http://localhost:8080/files/uploadFile
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: text/plain

<内容是上传的文件的实际内容>
--boundary--

###

### 测试获取目录中的文件和文件夹
GET http://localhost:8080/files/openDir?parent_id=

###

### 测试下载文件
GET http://localhost:8080/files/readFile?id=<文件ID>

###

### 测试删除文件夹
DELETE http://localhost:8080/files/deleteFCB?id=<文件夹ID>

###

### 测试删除文件
DELETE http://localhost:8080/files/deleteFCB?id=<文件ID>
